/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopproj;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrew
 */
public class FisherGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FisherGUI.class.getName());

    int persuaded = 0;
    int phase = 0;

    /**
     * Creates new form FactoryGUI
     */
    public FisherGUI() {
        initComponents();
        setInitialView();

    }

    public void setInitialView() {
        dialog1.setVisible(true);
        dialog2.setVisible(true);
        dialog3.setVisible(true);
        dialog1.setText("Your boat looks terrible get it off the sea.");
        dialog2.setText("Mind if I join you for some fishing?");
        dialog3.setText("You're overfishing in a protected zone, please move elsewhere!");

        fishermanTXTBOX.setEditable(false);
        fishermanTXTBOX.setText("What can I help you with?");

        pBar.setMinimum(0);
        pBar.setMaximum(3);
        pBar.setValue(0);

        Proceed.setVisible(false);
    }

    public void persuadeIncrease() {
        //Increment persuasion+phase
        persuaded++;
        phase++;

        //Update bar
        FisherProgress.increaseBar(pBar, persuaded);

        //proceed
        dialog1.setVisible(false);
        dialog2.setVisible(false);
        dialog3.setVisible(false);
        Proceed.setVisible(true);

        switch (persuaded) {
            case 1:
                fishermanTXTBOX.setText("Fisherman looks annoyed but listens.");
                dialog1.setText("you stink, its killing the fish.");
                dialog2.setText("nah I'm joking lets go fishing");
                dialog3.setText("The species of fish here are almost exinct.");
                break;
            case 2:
                fishermanTXTBOX.setText("Fisherman seems to be considering your point.");
                dialog1.setText("I'm never coming here again.");
                dialog2.setText("pass me a rod!");
                dialog3.setText("Your compliance will save entire species! And you wont go to jail!");
                break;
            case 3:
                fishermanTXTBOX.setText("The fisherman agrees to stop overfishing!");
                break;
        }

        if (persuaded >= pBar.getMaximum()) {
            JOptionPane.showMessageDialog(this, "The fisherman agrees to stop overfishing!");
            Proceed.setVisible(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomTitleLBL = new javax.swing.JLabel();
        ReturnBTN = new javax.swing.JButton();
        pBar = new javax.swing.JProgressBar();
        fishermanTXTBOX = new java.awt.TextArea();
        burnsLBL = new javax.swing.JLabel();
        burnsBackgroundPNL = new javax.swing.JPanel();
        pMeterLBL = new javax.swing.JLabel();
        responseLBL = new javax.swing.JLabel();
        Proceed = new javax.swing.JButton();
        dialog1 = new javax.swing.JButton();
        dialog2 = new javax.swing.JButton();
        dialog3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        factoryBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomTitleLBL.setText("Toby's vessel                            Objective: Convince the man to stop overfishing.");
        getContentPane().add(roomTitleLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        ReturnBTN.setText("Return to map");
        ReturnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 30));
        getContentPane().add(pBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 20));
        getContentPane().add(fishermanTXTBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 310, 180));

        burnsLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fisher.png"))); // NOI18N
        getContentPane().add(burnsLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 30, 310, 180));

        burnsBackgroundPNL.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout burnsBackgroundPNLLayout = new javax.swing.GroupLayout(burnsBackgroundPNL);
        burnsBackgroundPNL.setLayout(burnsBackgroundPNLLayout);
        burnsBackgroundPNLLayout.setHorizontalGroup(
            burnsBackgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        burnsBackgroundPNLLayout.setVerticalGroup(
            burnsBackgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(burnsBackgroundPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 310, 180));

        pMeterLBL.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        pMeterLBL.setText("The persuasion meter");
        getContentPane().add(pMeterLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));

        responseLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        responseLBL.setText("How do you respond?");
        getContentPane().add(responseLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 20));

        Proceed.setText("Proceed");
        Proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedActionPerformed(evt);
            }
        });
        getContentPane().add(Proceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 520, 40));

        dialog1.setText("Your boat looks terrible get it off the sea.");
        dialog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog1ActionPerformed(evt);
            }
        });
        getContentPane().add(dialog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 520, 40));

        dialog2.setText("Mind if I join you for some fishing?");
        dialog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog2ActionPerformed(evt);
            }
        });
        getContentPane().add(dialog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 520, 40));

        dialog3.setText("You're overfishing in a protected zone, please move elsewhere!");
        dialog3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialog3ActionPerformed(evt);
            }
        });
        getContentPane().add(dialog3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 520, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 800, 190));
        getContentPane().add(factoryBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialog3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog3ActionPerformed
        // TODO add your handling code here:
        persuadeIncrease(); //calls method
        FisherProgress.increaseBar(pBar, persuaded); //to other class

    }//GEN-LAST:event_dialog3ActionPerformed

    private void dialog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "you've been kicked off the ship for being rude.");
        SurfaceLvlGUI surfaceGUI = new SurfaceLvlGUI();
        surfaceGUI.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_dialog1ActionPerformed

    private void dialog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialog2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "your mission was not to go fishing, what the hell??");
        SurfaceLvlGUI surfaceGUI = new SurfaceLvlGUI();
        surfaceGUI.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_dialog2ActionPerformed

    private void ReturnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBTNActionPerformed
        // TODO add your handling code here:
        SurfaceLvlGUI surfaceGUI = new SurfaceLvlGUI();
        surfaceGUI.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_ReturnBTNActionPerformed

    private void ProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedActionPerformed
        // TODO add your handling code here:
        // Just show the next set of dialogs
        Proceed.setVisible(false);
        dialog1.setVisible(true);
        dialog2.setVisible(true);
        dialog3.setVisible(true);
    }//GEN-LAST:event_ProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FisherGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Proceed;
    private javax.swing.JButton ReturnBTN;
    private javax.swing.JPanel burnsBackgroundPNL;
    private javax.swing.JLabel burnsLBL;
    private javax.swing.JButton dialog1;
    private javax.swing.JButton dialog2;
    private javax.swing.JButton dialog3;
    private javax.swing.JLabel factoryBackground;
    private java.awt.TextArea fishermanTXTBOX;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar pBar;
    private javax.swing.JLabel pMeterLBL;
    private javax.swing.JLabel responseLBL;
    private javax.swing.JLabel roomTitleLBL;
    // End of variables declaration//GEN-END:variables
}
