/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopproj;

/**
 *
 * @author mncrf
 */
public class MidLvl2GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MidLvl2GUI.class.getName());
    private static CollectibleSystem collectibleSystem;
    /**
     * Creates new form MidLvl2GUI
     */
    public MidLvl2GUI() {
        initComponents();
        collectibleSetup();
    }
    
    private void collectibleSetup(){
        collectibleSystem = MidLvl1GUI.getCollectibleSystem();//allows the collectibles to sync
        if (collectibleSystem == null) {//creates new collectible system when its empty
            collectibleSystem = new CollectibleSystem();//wont work if this if statement with creating collectible system doesnt exist
        }
        collectibleSystem.createCollectible(shipLbl, "Ship Wreck");
        collectibleSystem.createCollectible(turtleLbl, "Injured Turtle");
        
        //https://clipart-library.com/clipart/shipwreck-cliparts-4.htm
        
        // checks for collectible if it was already found by reading the file
        loadCollectedItems();
        
        updateProgressBar();//updates Bar when found
    }
    
    private void updateProgressBar(){
        colCounter.setMaximum(4);//4 collectibles in both GUI's, thats why max is 4
        colCounter.setValue(collectibleSystem.getCollectionCount());//makes progress bar full when 4 collectibles collected, syncs with alll collectibles
    }
    
    private void loadCollectedItems() {//allows collectibles to be hidden when found and returned to the Coral Reef before closing the app.
        try(java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("CollectiblesProgress.txt"))) {
            String line;
            while((line = br.readLine()) != null) {
                if(line.contains("Ship Wreck") && line.contains("MidLvl2")) {
                    if(!collectibleSystem.isCollected(shipLbl)) {//prevents progress bar duplication and message popups
                        collectibleSystem.collectCollectibleSilent(shipLbl);
                    }
                    shipLbl.setVisible(false);
                }
                 if(line.contains("Injured Turtle") && line.contains("MidLvl2")) {//searches line Injured Turtle to correctly hide collected collectibles
                    if(!collectibleSystem.isCollected(turtleLbl)) {//prevents progress bar duplication and message popups
                        collectibleSystem.collectCollectibleSilent(turtleLbl);
                    }
                    turtleLbl.setVisible(false);
                }
            }
        } catch(java.io.IOException e) {
            // File doesn't exist yet, no items collected
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainBtn = new javax.swing.JButton();
        shipLbl = new javax.swing.JLabel();
        leftArrow = new javax.swing.JLabel();
        colCounter = new javax.swing.JProgressBar();
        displayBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        turtleLbl = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainBtn.setText("MainMenu");
        mainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mainBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        shipLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/C3 (2).png"))); // NOI18N
        shipLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shipLblMouseClicked(evt);
            }
        });
        getContentPane().add(shipLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 110, 90));

        leftArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Arrow1.png"))); // NOI18N
        leftArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftArrowMouseClicked(evt);
            }
        });
        getContentPane().add(leftArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 100));
        getContentPane().add(colCounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 40, 140, -1));

        displayBtn.setText("View Collectibles");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(displayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        deleteBtn.setText("Reset");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        turtleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Adobe Express - file (3).png"))); // NOI18N
        turtleLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                turtleLblMouseClicked(evt);
            }
        });
        getContentPane().add(turtleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 250, 100));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/midImg2.png"))); // NOI18N
        background2.setText("jLabel1");
        background2.setMaximumSize(new java.awt.Dimension(1000, 500));
        background2.setMinimumSize(new java.awt.Dimension(1000, 500));
        background2.setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtnActionPerformed
        // TODO add your handling code here:
        MainMenuGUI mainGUI= new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainBtnActionPerformed

    private void shipLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipLblMouseClicked
        // TODO add your handling code here:
        //https://clipart-library.com/clipart/shipwreck-cliparts-4.htm
        collectibleSystem.collectCollectible(shipLbl);//collectbile collected
        updateProgressBar();
        saveProgress("Ship Wreck");//saves collectbile and Ship wreck to the txt
    }//GEN-LAST:event_shipLblMouseClicked

    private void leftArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftArrowMouseClicked
        // TODO add your handling code here:
        MidLvl1GUI Mid1= new MidLvl1GUI();
        Mid1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leftArrowMouseClicked

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        // //insipiraion from lecture notes
        try(java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("CollectiblesProgress.txt"))) {
            String item;
            StringBuilder message = new StringBuilder("Collected Items:\n");
            item = br.readLine();
            while(item != null) {
                message.append(item).append("\n");
                item = br.readLine();
            }
            javax.swing.JOptionPane.showMessageDialog(this, message.toString());
        } catch(java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred while reading the file: " + e.getMessage());
        }
        
    }//GEN-LAST:event_displayBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        deleteProgress();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void turtleLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turtleLblMouseClicked
        // TODO add your handling code here:
        //https://www.dreamstime.com/brown-sea-turtle-icon-cartoon-stuck-sixpack-ring-plastic-isolated-vector-illustration-graphic-design-image149672385
        collectibleSystem.collectCollectible(turtleLbl);//collectbile collected
        updateProgressBar();
        saveProgress("Turtle");//saves collectible and turtle to the txt
    }//GEN-LAST:event_turtleLblMouseClicked
    
    private void deleteProgress() {
        Progress progress = new Progress("CollectiblesProgress.txt");
        progress.clearProgress();
        if(collectibleSystem != null) {
            collectibleSystem.resetCollectibles();
        }
        MainMenuGUI mainGUI = new MainMenuGUI();
        mainGUI.setVisible(true);
        this.dispose();
    }
    
    private void saveProgress(String collectibleName) {
        Progress progressHandler = new Progress("CollectiblesProgress.txt");
        progressHandler.saveCollectible(collectibleName, "MidLvl2");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MidLvl2GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background2;
    private javax.swing.JProgressBar colCounter;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel leftArrow;
    private javax.swing.JButton mainBtn;
    private javax.swing.JLabel shipLbl;
    private javax.swing.JLabel turtleLbl;
    // End of variables declaration//GEN-END:variables
}
