/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopproj;

import java.util.ArrayList;

/**
 *
 * @author Andrew
 */
public class OilGUI extends javax.swing.JFrame {

    int isOil;
    ArrayList<String> waterTreatment = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OilGUI.class.getName());

    /**
     * Creates new form OilGUI
     */
    public OilGUI() {
        initComponents();
        jProgressBar1.setMinimum(0);
        jProgressBar1.setMaximum(9);//num of oil tiles they gotta click
        jProgressBar1.setValue(0);   

    }

    public ArrayList<String> getWaterTreatment() {
        return waterTreatment;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBTN = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        oilToggleBTN = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        oilToggleBTN8 = new javax.swing.JToggleButton();
        oilToggleBTN6 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        oilToggleBTN5 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        oilToggleBTN2 = new javax.swing.JToggleButton();
        oilToggleBTN7 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        oilToggleBTN3 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        oilToggleBTN9 = new javax.swing.JToggleButton();
        oilToggleBTN4 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        returnBTN = new javax.swing.JButton();
        roomTitleLBL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkBTN.setText("Done");
        checkBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBTNActionPerformed(evt);
            }
        });
        getContentPane().add(checkBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 70));

        jToggleButton1.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 518, 100, 100));

        jToggleButton2.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 412, 100, 100));

        jToggleButton3.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 306, 100, 100));

        jToggleButton4.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 100, 100));

        jToggleButton5.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 200, 100, 100));

        jToggleButton6.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 306, 100, 100));

        jToggleButton7.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 518, 100, 100));

        jToggleButton8.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 412, 100, 100));

        oilToggleBTN.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTNActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 306, 100, 100));

        jToggleButton10.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 200, 100, 100));

        oilToggleBTN8.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN8ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN8, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 518, 100, 100));

        oilToggleBTN6.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN6ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN6, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 412, 100, 100));

        jToggleButton13.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 200, 100, 100));

        jToggleButton14.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 306, 100, 100));

        oilToggleBTN5.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN5ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 412, 100, 100));

        jToggleButton16.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 518, 100, 100));

        jToggleButton17.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 306, 100, 100));

        jToggleButton18.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 200, 100, 100));

        jToggleButton19.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 518, 100, 100));

        jToggleButton20.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 412, 100, 100));

        jToggleButton21.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 100));

        oilToggleBTN2.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN2ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 306, 100, 100));

        oilToggleBTN7.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN7ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 412, 100, 100));

        jToggleButton24.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 518, 100, 100));

        jToggleButton25.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 518, 100, 100));

        jToggleButton26.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 412, 100, 100));

        oilToggleBTN3.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN3ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 306, 100, 100));

        jToggleButton28.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 200, 100, 100));

        oilToggleBTN9.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN9ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN9, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 518, 100, 100));

        oilToggleBTN4.setBackground(new java.awt.Color(51, 51, 51));
        oilToggleBTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilToggleBTN4ActionPerformed(evt);
            }
        });
        getContentPane().add(oilToggleBTN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 200, 100, 100));

        jToggleButton31.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 306, 100, 100));

        jToggleButton32.setBackground(new java.awt.Color(0, 153, 204));
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 412, 100, 100));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 179, 854, 15));

        returnBTN.setText("Return to map");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(returnBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, -1, 36));

        roomTitleLBL.setText("Boat Oil spill               Objective: Remove the spilled oil from the ocean tiles!");
        getContentPane().add(roomTitleLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 453, 36));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Click on the oil tiles to clean them up! Progress :");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 420, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/oilspill.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 300, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void oilToggleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTNActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTNActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void oilToggleBTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN8ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN8.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN8ActionPerformed

    private void oilToggleBTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN6ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN6.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN6ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void oilToggleBTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN5ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN5.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN5ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN6.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void oilToggleBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN2ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN2.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN2ActionPerformed

    private void oilToggleBTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN7ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN7.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN7ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void oilToggleBTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN3ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN3.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN3ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void oilToggleBTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN9ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN9.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN9ActionPerformed

    private void oilToggleBTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilToggleBTN4ActionPerformed
        // TODO add your handling code here:
        if (oilToggleBTN4.isSelected()) {
            waterTreatment.add("oilTile");
        } else {
            waterTreatment.remove("oilTile");
        }
    }//GEN-LAST:event_oilToggleBTN4ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBTNActionPerformed
        // TODO add your handling code here:
        SurfaceLvl2 surface2 = new SurfaceLvl2();
        surface2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnBTNActionPerformed

    private void checkBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBTNActionPerformed
        // TODO add your handling code here:

        for (String treated : waterTreatment) {
            if ("oilTile".equals(treated)) {
                isOil++;
                System.out.println(isOil);
            }
        }

        System.out.println(waterTreatment);
        OilProgress.TreatmentProcess(waterTreatment, jProgressBar1);


    }//GEN-LAST:event_checkBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OilGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton oilToggleBTN;
    private javax.swing.JToggleButton oilToggleBTN2;
    private javax.swing.JToggleButton oilToggleBTN3;
    private javax.swing.JToggleButton oilToggleBTN4;
    private javax.swing.JToggleButton oilToggleBTN5;
    private javax.swing.JToggleButton oilToggleBTN6;
    private javax.swing.JToggleButton oilToggleBTN7;
    private javax.swing.JToggleButton oilToggleBTN8;
    private javax.swing.JToggleButton oilToggleBTN9;
    private javax.swing.JButton returnBTN;
    private javax.swing.JLabel roomTitleLBL;
    // End of variables declaration//GEN-END:variables
}
