/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopproj;

/**
 *
 * @author Andrew
 */
public class SurfaceLvlGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SurfaceLvlGUI.class.getName());

    /**
     * Creates new form SurfaceLvl2
     */
    public SurfaceLvlGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moveRightBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        factoryBTN = new javax.swing.JButton();
        returnFromSurfaceLvlButton = new javax.swing.JButton();
        backgroundLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moveRightBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Arrow2.png"))); // NOI18N
        moveRightBTN.setInheritsPopupMenu(true);
        moveRightBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveRightBTNActionPerformed(evt);
            }
        });
        getContentPane().add(moveRightBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jButton2.setText("boat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 90, 50));

        factoryBTN.setText("Factory");
        factoryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryBTNActionPerformed(evt);
            }
        });
        getContentPane().add(factoryBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 80));

        returnFromSurfaceLvlButton.setText("Return to Main Menu");
        returnFromSurfaceLvlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnFromSurfaceLvlButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnFromSurfaceLvlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        backgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/ocean.jpg"))); // NOI18N
        getContentPane().add(backgroundLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveRightBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveRightBTNActionPerformed
        // TODO add your handling code here:
        SurfaceLvl2 surface2 = new SurfaceLvl2();
        surface2.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_moveRightBTNActionPerformed

    private void factoryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryBTNActionPerformed
        // TODO add your handling code here:
        FactoryGUI factory = new FactoryGUI();
        factory.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_factoryBTNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FisherGUI fisher = new FisherGUI();
        fisher.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void returnFromSurfaceLvlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnFromSurfaceLvlButtonActionPerformed
        // TODO add your handling code here:
        new MainMenuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnFromSurfaceLvlButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SurfaceLvlGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLBL;
    private javax.swing.JButton factoryBTN;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton moveRightBTN;
    private javax.swing.JButton returnFromSurfaceLvlButton;
    // End of variables declaration//GEN-END:variables
}
